apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vector-db-leader-election
  namespace: default
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vector-db-leader-election
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: vector-db-leader-election
  apiGroup: rbac.authorization.k8s.io

